### ISSUE TITLE
Shortcut to move focus to commit message input

### ISSUE THREAD

**Issue by dannypernik** [FloppyDisco/git-stage-file#5] opened 2024-11-05 06:05 UTC
I've been playing around with the extension to find my optimal workflow. First, I switched to a global shortcut to open quickstage so that I don't need extra keypresses to focus the git sidebar.

Once I've staged the relevant files, my next step is always to write a commit message. I would love to have a shortcut that was active when QuickStageVisible that would show scm view if hidden and focus on the commit message input. (I have a minimalist setup that only shows one sidebar view at a time, and with my global shortcut, there's no need for scm to be visible in order to stage files with quickStage.)

For what it's worth, I believe the tool you're building should be native functionality!

**Comment by FloppyDisco** [comment] 2024-11-05 19:47
Thank you! I also agree that the SCM sidebar should pretty much have this type of keyboard functionality by default.

This feature should be simple enough to add, I already had it focus the SCM view in a previous version, but I like the idea of having a dedicated shortcut for it. I have the options in the list for `stage all` and `unstage all` that can be run by selecting them with (space) or (enter) OR by pressing the keybinding. Do you think it would be worth having a similar item for the commit message? or just the keybinding? I personally press the keybinding more often, but i think it's nice to have that visual reminder of what the keybinding is. 

`cmd+c` or `cmd+g` what do you think? lol

**Comment by FloppyDisco** [comment] 2024-11-05 23:24
<img width="900" alt="Screenshot 2024-11-06 at 12 08 33 AM" src="https://github.com/user-attachments/assets/180ef8c6-4e09-4876-b36a-eeda97c97eb8">

So i added a few new features with this most recent update `0.3.3`
i swapped `enter` with `space` as you suggested. so `enter` now stages the files and `space` will diff the file.

I added some more user customizable settings, trying to fit as many use cases as i could. 
QuickStage will now focus the SCM view automatically on exit, you can turn this off in the settings if you don't like it.
there are also 2 settings for the diff previews
I think the behavior you are looking for is 

```
"quickStage.previewDiff": true,
"quickStage.closePreviewOnExit: false,
"quickStage.focusScmSidebarOnExit: false,
```
I think this is what you were wanting, but maybe try out the autoFocus and see if you like it without using the extra keybinding to open SCM. 

My user story is:
- open QuickStage
- preview a file and stage it
- press 'Esc' and move to SCM to write commit message.
- The preview Diff that was open closes, leaving my workspace uncluttered.

you can read more on these in the readme, but you'll probably also want to set `"scm.autoReveal": false,` to make sure the SCM view always focuses the commit box!

**Comment by FloppyDisco** [comment] 2024-11-06 09:55
So i actually had a bit more of a think on this, and I removed the focus SCM keybinding from the extension.
Simply because it already exists. the default keybinding to focus the SCM view is `cmd+ctrl+g` and you can change it to whatever you want.
```
  {
    "key": "your+keybinding",
    "command": "workbench.view.scm",
    "when": "workbench.scm.active"
  },
```
this along with `"scm.autoReveal": false,` will give you the functionality you were looking for here. and it will open the commit message at any time whether quickStage is open or not. 
if you want it to only work when quickStage is open you can use this when statement.
`"when": "workbench.scm.active && QuickStageVisible",`

hope that helps!

**Comment by dannypernik** [comment] 2024-11-06 16:17
Looking great! Thanks a lot for taking my suggestion about enter vs space. Is `quickStage.focusScmSidebarOnExit` still an active setting? It gets greyed out in my settings.json as if it's not recognized. I do have a keybinding set for `workbench.view.scm`.

With regards to focusing the commit input, there's a weird native quirk that is also present when using quickStage. When I use my `workbench.view.scm` or press Esc from inside quickStage, there are times that commit input is focused and other times it's not. Specifically, it looks like if the most recent SCM focus is on an element within the scm view (such as on a file like in this first screenshot), the focus returns to that item by the keybinding or Esc:

![image](https://github.com/user-attachments/assets/fe91c77e-5b82-4954-89c2-5d69e0296cc8)

However, if the most recent focus is on the view as a whole (as in this 2nd screenshot), the commit input is focused on keypress:

![image](https://github.com/user-attachments/assets/ae2eb4f4-e9d7-4bc9-889f-73f1eb7563b3)

Actually, it appears that the focus is passed to each file in scm view when traversing files in quickStage, so the commit input is not focused if quickStage has been utilized. Hopefully it's an easy fix. And no worries if not! Let me know if you'd like me to create a separate issue. For the record, here are the quickStage settings I've set (the 2nd of which does not appear to be recognized):

```
"quickStage.previewDiff": true,
"quickStage.closePreviewOnExit": false
```

**Comment by FloppyDisco** [comment] 2024-11-06 17:04
I have `0.3.5` installed on my machine, the settings should all be there. does `focusScmSidebarOnExit` appear in the settings GUI?
<img width="1261" alt="Screenshot 2024-11-06 at 6 02 31 PM" src="https://github.com/user-attachments/assets/d92179a2-e90c-4947-8c71-156013e8b697">
<img width="821" alt="Screenshot 2024-11-06 at 6 03 45 PM" src="https://github.com/user-attachments/assets/0f157b97-5a17-46a2-acaa-110425cae65b">

**Comment by FloppyDisco** [comment] 2024-11-06 17:06
i believe the behavior you are experiencing is `"scm.autoReveal"` this is what is moving the focus to the specific file. 
set this to false and see if it fixes it!

**Comment by FloppyDisco** [comment] 2024-11-06 22:23
just a heads up i added a global keybinding for Quick Stage in `0.3.7` so you may need to change it in your settings again to make sure it doesn't conflict with the keybinding you already set.

**Comment by dannypernik** [comment] 2024-11-07 06:19
Here's what I'm getting when exiting quickStage with Escape on `v0.3.7` with `"scm.autoReveal": false`. You can also see my settings at the end of the clip:
[Screen Recording 2024-11-06 at 11.42.53 PM.webm](https://github.com/user-attachments/assets/c7427e36-143e-4b09-bb00-276e689fb7b1)

I'm only seeing one quickStage setting in the GUI:
![Screenshot 2024-11-06 at 11 40 20 PM](https://github.com/user-attachments/assets/e0c16f53-1c0a-4fc0-8764-a3ff1be7d5a2)

The 2 keybindings don't appear to have a different behavior, but I'm actually hoping not to rely on it anyway since it doesn't consistently focus the commit message.

**Comment by FloppyDisco** [comment] 2024-11-07 10:17
here's a video of it focusing the input box. I commented out all of my settings and only set `"scm.autoReveal": false`
seems to be working for me here.

https://github.com/user-attachments/assets/4e4cefff-9a6b-4bf9-b931-c996d899a472

**Comment by FloppyDisco** [comment] 2024-11-07 18:21
ok cool! glad it is working. 
I see the behavior you are talking about. unfortunately there is not a command that allows us to directly focus the commit input box, so we can only open the view and use the native functionality to direct where the focus goes.
On my machine it actually only seems to focus back to the list of changes if i open QuickStage, DO NOTHING, and then close it. If i stage a file using Quick Stage, then close it, it focuses the input box correctly even if i was just previously focused on the list of changes. 

i'm gonna go ahead and close this as it seem like the functionality is about as good as we can get it, and it works as intended most of the time. please let me know if you have more issues or suggestions! i appreciate the help with this!

**Closed by FloppyDisco** 2024-11-07 18:21 UTC
